# Generated by Django 3.2.7 on 2021-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_userdata_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userid',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
