# Generated by Django 3.2.7 on 2021-10-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_userdetails_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='vrmodel',
            field=models.FileField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
