# Generated by Django 3.2.7 on 2021-10-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20211011_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='image2',
            field=models.FileField(null=True, upload_to='products/'),
        ),
    ]
