# Generated by Django 3.2.7 on 2021-10-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auctionlisting_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='startBid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.userdetails')),
            ],
        ),
    ]
