# Generated by Django 3.2.7 on 2021-10-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20211027_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp',
        ),
    ]
